# Generated by Django 4.2.7 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="alias",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
