# Generated by Django 4.2.7 on 2023-12-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="URL",),
    ]
